veriosn 2.0
jobs: 
  build: 
    docker: 
     - image: circleci/node:4.8.2
    working_directory: /infra
    steps: 
      - checkout # check out the source code
      - run: 
       name: a simple hellow world job
       command: |
 	echo "Hello, World!"
  
