version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    working_directory: /infra
    steps:
      - checkout # Checks out the source code
      - run: 
        name: hellow_world
        command: echo "Hello World!"
